#!/bin/sh
dev=atbm603x-gk7205v300-xm-g6s #Marco dev=$(fw_printenv -n wlandev)
mac=$(fw_printenv -n wlanmac)
net=$(fw_printenv -n netaddr_fallback)

echo "Marco: running C:\Users\WIN11-TOGO\Documents\GitHub\firmware\general\overlay\etc\init.d"

set_wireless() {
	path=/etc/wireless
	if $path/usb "$dev" || $path/sdio "$dev"; then
		[ -n "$mac" ] && ip link set dev wlan0 address "$mac"
		ifup -v wlan0
	elif $path/modem "$dev"; then
		ifup usb0
		ifup eth1
	fi
	[ -e /sys/class/net/eth0 ] && ifconfig eth0 "${net:-192.168.1.20}"
}

case "$1" in
	start)
		echo "Starting network..."
		ifup -v lo
		 if [ -n "$dev" ]; then
			set_wireless
		 else
			ifup -v eth0
		 fi
		;;

	stop)
		echo "Stopping network..."
		ifdown lo
		ifdown -f wlan0
		ifdown -f usb0
		ifdown -f eth1
		ifdown -f eth0
		;;

	restart)
		"$0" stop
		"$0" start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
